seed: 42

data:
  db_path: "db/app.db"
  sql_train: |
    SELECT id, text, label
    FROM train_table
    WHERE label IN (0,1)
  id_col: "id"
  text_col: "text"
  label_col: "label"

features:
  # Вариант 1: TF-IDF (офлайн fit, быстрее на инференсе)
  use_hashing: false
  tfidf:
    max_features: 5000
    ngram_range: [1, 2]
    lowercase: false
  # Вариант 2: HashingVectorizer (стриминговый, без fit)
  hashing:
    n_features: 1048576
    alternate_sign: false
    ngram_range: [1, 2]

cv:
  kind: "StratifiedKFold"   # или "KFold"
  n_splits: 5
  shuffle: true

metrics:
  # Имён достаточно, реализацию возьмём из sklearn.metrics
  - "accuracy"
  - "f1"
  - "roc_auc"
  - "log_loss"

save:
  dir: "models"                # корневая папка артефактов
  pattern: "{ts}/{model_name}" # подпапка на модель/запуск
  # итоговые файлы: sklearn -> model.joblib; keras -> keras_model/

db_log:
  enable: true
  db_path: "db/experiments.db"
  # таблицы создадим автоматически, см. ниже

active_models:
  - "logreg"
  - "rf"
  - "svm_rbf"
  - "nb"
  - "keras_mlp"

models:
  logreg:
    type: "sklearn.linear_model.LogisticRegression"
    params:
      max_iter: 1000
      class_weight: "balanced"
      n_jobs: -1
    # опц.: сетка под GridSearchCV
    grid: { C: [0.1, 1.0, 10.0] }

  rf:
    type: "sklearn.ensemble.RandomForestClassifier"
    params:
      n_estimators: 300
      max_depth: null
      n_jobs: -1
      class_weight: "balanced"

  svm_rbf:
    type: "sklearn.svm.SVC"
    params:
      kernel: "rbf"
      C: 3.0
      gamma: "scale"
      probability: true
      class_weight: "balanced"

  nb:
    type: "sklearn.naive_bayes.MultinomialNB"
    params:
      alpha: 0.1

  keras_mlp:
    type: "keras_mlp"     # нестандартный тип — обрабатываем отдельно
    params:
      hidden_units: 128
      dropout: 0.3
      lr: 0.001
      batch_size: 512
      epochs: 5