from .lfs import *

LFS = [
    lf_C2065_FIX_NAME_SPELLING,
    lf_C2065_HEADER_OR_STD_NAMESPACE,
    lf_C3861_FIX_NAME_SPELLING,
    lf_C3861_HEADER_OR_STD_NAMESPACE,
    lf_C2146_INCORRECT_CONSTRUCTION_OR_SYMBOLS,
]

__all__ = [
    "lf_C2065_HEADER_OR_STD_NAMESPACE",
    "lf_C2065_FIX_NAME_SPELLING",
    "lf_C3861_HEADER_OR_STD_NAMESPACE",
    "lf_C3861_FIX_NAME_SPELLING",
    "lf_C2146_INCORRECT_CONSTRUCTION_OR_SYMBOLS",
]